### ISSUE TITLE
Rust features to choose which runtime to compile

### ISSUE THREAD

**Issue by radu-matei** [deislabs/wasi-nn-onnx#16]
ref #4 
ref #10 

#15 added support for Tract, which means we should be able to compile a binary that does not need any shared libraries to run.

I already defining the features in the implementation crate's `Cargo.toml`, but they are still both enabled by default, and they are not selected in the binary:

```toml
[features]
default = ["c_onnxruntime", "tract"]

c_onnxruntime = ["onnxruntime"]
tract = ["tract-onnx"]
```

Then, in the binary:

```toml
[features]
c_onnxruntime = ["wasi-nn-onnx-wasmtime/c_onnxruntime"]
tract = ["wasi-nn-onnx-wasmtime/tract"]
```

The goal is to be able to compile a version of the binary that *only* uses Tract, so no shared libraries are required.
